---
dist: bionic
language: python

python:
  - "3.7"

services: 
  - docker

env:
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804

cache:
  directories:
    - /home/travis/.cache/pipenv

install:
  - curl -skL https://bootstrap.pypa.io/get-pip.py | python3
  - pip3 install pipenv
  - pipenv install

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
