---
- name: Ensure ~/.docker exists
  file:
    path: "~/.docker"
    state: directory
    owner: "{{item.username}}"
    group: "{{item.group}}"
  with_items: "{{docker_users}}"

- name: Update ~/.docker/config.json
  template:
    src: config.json.j2
    dest: ~/.docker/config.json
    owner: "{{item.username}}"
    group: "{{item.group}}"
  with_items: "{{docker_users}}"
