---
- name: Prepare
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Create docker network
      docker_network:
        name: proxy_network
        driver: bridge
        attachable: yes
        ipam_config:
          - subnet: 172.10.0.0/24
            gateway: 172.10.0.1
